name: Web Index Generator
author: Josh Beard
description: Generates index files for directories or S3 buckets
inputs:
  base_url:
    description: base_url specifies a URL to prefix to links, rather than relative links
    required: false
  config:
    description: path to a config file
    required: false
  date_format:
    description: The date format
    required: false
  dirs_first:
    description: List directories first (default true)
    required: false
  index_file:
    description: The name of the file to generate
    required: false
  link_to_index:
    description: >
      link to index will link to "index.html" for paths instead of just the path.
      e.g. foo/ vs foo/index.html
    required: false
  link_up_from_root:
    description: Show a parent/up link even when at the root of the indexed path
    required: false
  link_up_text:
    description: Text to display for the up link from root (default "Go Up")
    required: false
  link_up_url:
    description: URL path for the up link from root (default "..")
    required: false
  log_level:
    description: >
      The verbosity of output (info, error, warn, debug)
    required: false
  minify:
    description: Boolean toggling minification of the generated HTML
  noindex-files:
    description: 'A list of files that indicate a directory should be skipped'
    required: false
  order:
    description: 'The order for the items. One of: asc, desc'
  recursive:
    description: Index files recursively
  skip:
    description: a comma-separated list of files to skip
    required: false
  sort_by:
    description: The order for the index page. One of last_modified, name, natural_name (default "natural_name")
    required: false
  source:
    description: The source directory or S3 URI
    required: false
  target:
    description: The target directory or S3 URI
    required: false
  template:
    description: path to a custom Go template to use for the index file
    required: false
  title:
    description: title is shown at the top of the pages
    required: false
  image_tag:
    description: 'The Docker image tag to use (e.g., latest, dev-pr123)'
    required: false
    default: 'latest'
  skipindex-files:
    description: 'A list of files that indicate a directory should be skipped for indexing but still included in the parent directory listing'
    required: false
  image_tag:
    description: 'The Docker image tag to use (e.g., latest, dev-pr123)'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: ghcr.io/joshbeard/web-indexer/web-indexer:${{ inputs.image_tag }}
  env:
    BASE_URL: ${{ inputs.base_url }}
    DATE_FORMAT: ${{ inputs.date_format }}
    DIRS_FIRST: ${{ inputs.dirs_first }}
    INDEX_FILE: ${{ inputs.index_file }}
    LINK_TO_INDEX: ${{ inputs.link_to_index }}
    LINK_UP_FROM_ROOT: ${{ inputs.link_up_from_root }}
    LINK_UP_TEXT: ${{ inputs.link_up_text }}
    LINK_UP_URL: ${{ inputs.link_up_url }}
    LOG_LEVEL: ${{ inputs.log_level }}
    MINIFY: ${{ inputs.minify }}
    NOINDEX_FILES: ${{ inputs.noindex-files }}
    SKIPINDEX_FILES: ${{ inputs.skipindex-files }}
    ORDER: ${{ inputs.order }}
    RECURSIVE: ${{ inputs.recursive }}
    SKIP: ${{ inputs.skip }}
    SORT: ${{ inputs.sort }}
    SOURCE: ${{ inputs.source }}
    TARGET: ${{ inputs.target }}
    TEMPLATE: ${{ inputs.template }}
    TITLE: ${{ inputs.title }}
    CONFIG: ${{ inputs.config }}

branding:
  icon: globe
  color: orange
