# -----------------------------------------------------------------------------
# Web-Indexer Demo Configuration
# -----------------------------------------------------------------------------

demo:
  name: "web-indexer-demo"
  title: "Web-Indexer Demo"
  description: "Demonstration of web-indexer capabilities with multiple themes and configurations"

# S3 Configuration
s3:
  bucket_prefix: "joshbeard-web-indexer-demo"
  region: "us-east-1"

# Local Server Configuration
server:
  port: 8080

# List of demos to generate
demos:
  - name: theme.default
    title: "Theme: Default"
    description: "Clean, minimal design with automatic light/dark mode"
    args: "--theme default --recursive --title 'Default Theme Demo - {relativePath}'"
    directory: "theme.default"

  - name: theme.solarized
    title: "Theme: Solarized"
    description: "Based on the popular Solarized color scheme"
    args: "--theme solarized --recursive --title 'Solarized Theme Demo - {relativePath}'"
    directory: "theme.solarized"

  - name: theme.nord
    title: "Theme: Nord"
    description: "Arctic-inspired colors from the Nord palette"
    args: "--theme nord --recursive --title 'Nord Theme Demo - {relativePath}'"
    directory: "theme.nord"

  - name: theme.dracula
    title: "Theme: Dracula"
    description: "Vibrant, high-contrast dark theme"
    args: "--theme dracula --recursive --title 'Dracula Theme Demo - {relativePath}'"
    directory: "theme.dracula"