name: Release

on:
  push:
    tags:
      - "*.*.*"

# Allow creating releases and packages.
permissions:
  packages: write
  contents: write

jobs:
  goreleaser:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto

    steps:
      - uses: actions/checkout@v4 # v3.3.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.24.4'
          cache: true

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}

      - name: Prepare GPG signing key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" > key.gpg

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          NFPM_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
          NFPM_TESTPKG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Test packages
        run: make test-packages VERSION="${{ steps.get_version.outputs.VERSION }}"

  docker-hub-doc:
    name: Publish DockerHub Readme
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/web-indexer
          readme: ./README.md
          description: Generate file indexes for directories and S3 buckets
