name: "Lint & Test"
on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: check-vuln
        run: make check-vuln

      - name: Run gosec
        # Use a more recent version of gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -exclude-dir=vendor -exclude-dir=demo ./...
        env:
          GOTOOLCHAIN: auto

  lint:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Test
        run: make coverage
